export const AUDIT_ACTIONS = {
  // Task Actions
  CREATE_TASK: "CREATE_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  DELETE_TASK: "DELETE_TASK",
  UPDATE_TASK_STATUS: "UPDATE_TASK_STATUS",

  // Project Actions
  CREATE_PROJECT: "CREATE_PROJECT",
  UPDATE_PROJECT: "UPDATE_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
  PROJECT_MEMBER_ADDED: "PROJECT_MEMBER_ADDED",
  PROJECT_MEMBER_REMOVED: "PROJECT_MEMBER_REMOVED",

  // User Actions
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_REGISTER: "USER_REGISTER",
  CHANGE_USER_STATUS: "CHANGE_USER_STATUS",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",

  // Notification Actions
  MARK_NOTIFICATION_READ: "MARK_NOTIFICATION_READ",
  MARK_ALL_NOTIFICATIONS_READ: "MARK_ALL_NOTIFICATIONS_READ",
  DELETE_NOTIFICATION: "DELETE_NOTIFICATION",
  CLEAR_ALL_NOTIFICATIONS: "CLEAR_ALL_NOTIFICATIONS",

  // Department Actions
  CREATE_DEPARTMENT: "CREATE_DEPARTMENT",
  UPDATE_DEPARTMENT: "UPDATE_DEPARTMENT",
  DELETE_DEPARTMENT: "DELETE_DEPARTMENT",

  // Team Actions
  CREATE_TEAM: "CREATE_TEAM",
  UPDATE_TEAM: "UPDATE_TEAM",
  DELETE_TEAM: "DELETE_TEAM",
  TEAM_MEMBER_ADDED: "TEAM_MEMBER_ADDED",
  TEAM_MEMBER_REMOVED: "TEAM_MEMBER_REMOVED",

  // Leaves Actions
  CREATE_LEAVE: "LEAVE_APPLIED",

  // Attendance Actions
  CHECK_IN: "CHECK_IN",
  CHECK_OUT: "CHECK_OUT",
  ATTENDANCE_UPDATED: "ATTENDANCE_UPDATED",
};
