export const NOTIFICATION_TYPES = {
  TASK_CREATED: "TASK_CREATED",
  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_STATUS_UPDATED: "TASK_STATUS_UPDATED",
  PROJECT_UPDATED: "PROJECT_UPDATED",
  PROJECT_MEMBER_ADDED: "PROJECT_MEMBER_ADDED",
  PROJECT_MEMBER_REMOVED_REMOVED: "PROJECT_MEMBER_REMOVED_REMOVED",
  BIRTHDAY_REMINDER: "BIRTHDAY_REMINDER",
};
